/* automatically generated by rust-bindgen */

/* Then pruned by hand to keep only the needed parts. */


#[link(name = "krb5")]
#[link(name = "k5crypto")]
#[link(name = "com_err")]
extern "C" {
    pub fn com_err(arg1: *const ::libc::c_char, arg2: ::libc::c_long,
                   arg3: *const ::libc::c_char, ...) -> ();
}
